---
# Run with:
# ansible-playbook -i hosts --ask-become-pass 02_provision.yml

- hosts: all

  become: yes
  become_method: su
  become_user: root
  gather_facts: False

  tasks:
    - name: Update system
      dnf:
        name: "*"
        state: latest

    - name: Install stuff
      dnf:
        name:
          - nano  # lame editor (still better than vi/vim)
          - policycoreutils-python-utils  # needed to change SELinux port
          - dnf-automatic  # enable automatic updates (see below)
          - cryptsetup  # for decrypting external drives
          - crontabs  # for periodic cert renewal
        state: present

    - name: Set hostname
      hostname:
        name: nil

    - name: Disable IPv6
      lineinfile:
        path: /etc/sysctl.conf
        regexp: "{{ item }}"
        line: "{{ item }} = 1"
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6

    - name: Disable mdns service in firewalld
      firewalld:
        service: mdns
        permanent: yes
        state: disabled
      notify: Reload firewalld

    - name: Disable dhcpv6-client service in firewalld
      firewalld:
        service: dhcpv6-client
        permanent: yes
        state: disabled
      notify: Reload firewalld

    - name: Enable automatic updates
      lineinfile:
        dest: /etc/dnf/automatic.conf
        regexp: "^apply_updates = "
        line: "apply_updates = yes"

    - name: Only apply security updates
      lineinfile:
        dest: /etc/dnf/automatic.conf
        regexp: "^upgrade_type = "
        line: "upgrade_type = security"

    - name: Add update log motd
      lineinfile:
        dest: /etc/dnf/automatic.conf
        regexp: "^emit_via = "
        line: "emit_via = motd"

    - name: Enable a timer for dnf-automatic
      systemd:
        name: dnf-automatic.timer
        state: started
        enabled: yes

  handlers:
    - name: Reload firewalld
      command: firewall-cmd --reload
