---
# Run with:
# ansible-playbook -i hosts --ask-become-pass 03_nginx.yml

- hosts: all

  vars_prompt:
  - name: certbot_email
    prompt: "Enter email address for certbot renewal and security notices"
    private: no

  become: yes
  become_method: su
  become_user: root
  gather_facts: False

  tasks:
    - name: Ditch httpd
      dnf:
        name: httpd
        state: absent

    - name: Allow https service in firewalld
      firewalld:
        service: https
        permanent: yes
        state: enabled

    - name: Allow http service in firewalld
      firewalld:
        service: http
        permanent: yes
        state: enabled
      notify: Reload firewalld

    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Check if dhparams.pem already exists
      stat:
        path: /etc/letsencrypt/live/nil.bz/cert.pem
      register: letsencrypt_cert

    - name: Generate Diffie-Hellman parameters with size 4096 bits
      openssl_dhparam:
        path: /etc/ssl/dhparams.pem

    - name: Install certbot and its Nginx plug-in
      dnf:
        name: certbot-nginx
        state: present

    - name: Check if certificate already exists
      stat:
        path: /etc/letsencrypt/live/nil.bz/cert.pem
      register: letsencrypt_cert

    - name: "Set up Let's Encrypt certs"
      shell: certbot certonly --nginx --agree-tos --non-interactive -m {{ certbot_email }} -d nil.bz
      when: not letsencrypt_cert.stat.exists
      notify: Restart nginx

    - name: Copy nginx.conf
      copy:
        src: etc_nginx_nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: Restart nginx

    - name: Copy nilbz.conf
      copy:
        src: etc_nginx_confd_nilbz.conf
        dest: /etc/nginx/conf.d/nilbz.conf
      notify: Restart nginx

    - name: Create /var/www
      file:
        path: /var/www/temp
        state: directory
        mode: 0755
        recurse: yes
      register: www_created

    - name: Apply correct SELinux file context /var/www
      command: restorecon -irv /var/www
      when: www_created.changed

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes

    - name: Reload firewalld
      command: firewall-cmd --reload
